version: '3.8'
services:

  backend:
    build: ./backend/
    container_name: nest_backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    networks:
      - ft_transcendence
    restart: always
    depends_on:
      - db-postgres
    entrypoint: sh -c "
                      if [ ! -d /app/prisma/migrations ]; 
                          then npx prisma migrate dev --name init --preview-feature;
                      fi; npm run start:dev;"

  db-postgres:
    image: postgres
    container_name: db-postgres
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    networks:
      - ft_transcendence
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  frontend:
    build: ./frontend/
    container_name: next_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    networks:
      - ft_transcendence
    restart: always
    depends_on:
      - backend

networks:
  ft_transcendence:
    driver: bridge

volumes:
  pgdata:
